### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Binngs3** [A1exy/Android_FacialExpressionRecognition#4]
你好 我环境配置好了之后发现预测表情的时候一直闪退，错误信息如下 我也不知道怎么修复，您能帮我看一下是什么问题导致的吗，我搜了下好像是数组越界的问题

04-10 03:41:18.875 2061-2061/com.example.alex.opencvdemo A/libc: Fatal signal 11 (SIGSEGV) at 0xdead0000 (code=1), thread 2061 (alex.opencvdemo)

**Comment by A1exy** [comment]
你的Android版本是多少，在手机上测试的吗？

**Comment by A1exy** [comment]
我当时Android系统的版本很旧，拍照这部分功能可能需要你根据系统版本调整下，其他的逻辑应该没有问题。

**Comment by Binngs3** [comment]
我是用的安卓4.4 在genymotion上用安卓虚拟机测试的 请问你的安卓是哪个版本呢

**Comment by A1exy** [comment]
我当时是拿安卓手机测试的 虚拟机拍照部分有问题  当时虚拟机测试不行  所以我找了个安卓手机测试的 手机版本我晚上回去找到了再回复你

**Comment by Binngs3** [comment]
对我大概知道问题的原因了 虚拟机用的摄像头拍出来的照片是宽的 可能尺寸不对 我也去找个安卓手机测试一下
